# Generated by Django 3.0.5 on 2020-05-05 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('title', models.CharField(max_length=150)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('current', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warfare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar', models.BooleanField(default=True)),
                ('posts', models.ManyToManyField(to='axis.Post')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axis.Project')),
                ('questions', models.ManyToManyField(to='axis.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar', models.BooleanField(default=True)),
                ('posts', models.ManyToManyField(to='axis.Post')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axis.Project')),
                ('questions', models.ManyToManyField(to='axis.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar', models.BooleanField(default=True)),
                ('posts', models.ManyToManyField(to='axis.Post')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axis.Project')),
                ('questions', models.ManyToManyField(to='axis.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar', models.BooleanField(default=True)),
                ('posts', models.ManyToManyField(to='axis.Post')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axis.Project')),
                ('questions', models.ManyToManyField(to='axis.Question')),
            ],
        ),
    ]
