# Generated by Django 3.0.5 on 2020-05-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Describe your project here.', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='Give your project a name!', max_length=100),
        ),
    ]
