# Generated by Django 3.0.5 on 2020-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis', '0002_culture_post_question_warfare'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='default title', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
