# Generated by Django 3.0.5 on 2020-05-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis', '0003_auto_20200505_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='domain',
            field=models.TextField(default='Miscellaneous'),
        ),
    ]
