# Generated by Django 3.0.5 on 2020-05-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis', '0007_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.CharField(choices=[('Sum', 'Summary'), ('Shd', 'Section Header'), ('Ssc', 'Subsection')], default='Ssc', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
